/* Newtuple approved reference assets — GENERATED by tools/build_library.py.
   Drop files into uploads/approved/ then re-run. Do not hand-edit. */
window.NT_REFERENCES = [
  {
    "file": "../uploads/approved/fable5-carousel.pptx",
    "thumb": "ref-thumbs/uploads-approved-fable5-carousel.png",
    "title": "fable5 carousel",
    "type": "deck",
    "ext": "pptx",
    "group": "approved"
  },
  {
    "file": "../uploads/approved/Geometric-Curves.png",
    "thumb": "ref-thumbs/uploads-approved-geometric-curves.png",
    "title": "Geometric Curves",
    "type": "image",
    "ext": "png",
    "group": "approved"
  },
  {
    "file": "../uploads/approved/GP-Newtuple%20Design%20Guidelines%20-%20New-140526-090223.pdf",
    "thumb": "ref-thumbs/uploads-approved-gp-newtuple-design-guidelines-new-140526-090223.png",
    "title": "GP Newtuple Design Guidelines New 140526 090223",
    "type": "pdf",
    "ext": "pdf",
    "group": "approved"
  },
  {
    "file": "../uploads/approved/Logo_dark_background.png",
    "thumb": "ref-thumbs/uploads-approved-logo-dark-background.png",
    "title": "Logo dark background",
    "type": "image",
    "ext": "png",
    "group": "approved"
  },
  {
    "file": "../uploads/approved/Logo_light_background.png",
    "thumb": "ref-thumbs/uploads-approved-logo-light-background.png",
    "title": "Logo light background",
    "type": "image",
    "ext": "png",
    "group": "approved"
  },
  {
    "file": "../uploads/approved/Newtuple_OnePager%20%281%29.pdf",
    "thumb": "ref-thumbs/uploads-approved-newtuple-onepager-1.png",
    "title": "Newtuple OnePager (1)",
    "type": "pdf",
    "ext": "pdf",
    "group": "approved"
  },
  {
    "file": "../uploads/approved/Pension_Contribution_Processing_Automation_-_Newtuple_Proposal%20%284%29%20%283%29.pptx",
    "thumb": "ref-thumbs/uploads-approved-pension-contribution-processing-automation-newtuple-proposal-4-3.png",
    "title": "Pension Contribution Processing Automation Newtuple Proposal (4) (3)",
    "type": "deck",
    "ext": "pptx",
    "group": "approved"
  }
];
