/* Newtuple approved reference assets — GENERATED by tools/build_library.py.
   Drop files into uploads/approved/ then re-run. Do not hand-edit. */
window.NT_REFERENCES = [
  {
    "file": "../uploads/approved.pptx",
    "thumb": "ref-thumbs/uploads-approved.png",
    "title": "approved",
    "type": "deck",
    "ext": "pptx",
    "group": "approved"
  },
  {
    "file": "../uploads/approved/fable5-carousel.pptx",
    "thumb": "ref-thumbs/uploads-approved-fable5-carousel.png",
    "title": "fable5 carousel",
    "type": "deck",
    "ext": "pptx",
    "group": "approved"
  },
  {
    "file": "../uploads/approved/Geometric-Curves.png",
    "thumb": "ref-thumbs/uploads-approved-geometric-curves.png",
    "title": "Geometric Curves",
    "type": "image",
    "ext": "png",
    "group": "approved"
  },
  {
    "file": "../uploads/approved/GP-Newtuple%20Design%20Guidelines%20-%20New-140526-090223.pdf",
    "thumb": "ref-thumbs/uploads-approved-gp-newtuple-design-guidelines-new-140526-090223.png",
    "title": "GP Newtuple Design Guidelines New 140526 090223",
    "type": "pdf",
    "ext": "pdf",
    "group": "approved"
  },
  {
    "file": "../uploads/approved/Logo_dark_background.png",
    "thumb": "ref-thumbs/uploads-approved-logo-dark-background.png",
    "title": "Logo dark background",
    "type": "image",
    "ext": "png",
    "group": "approved"
  },
  {
    "file": "../uploads/approved/Logo_light_background.png",
    "thumb": "ref-thumbs/uploads-approved-logo-light-background.png",
    "title": "Logo light background",
    "type": "image",
    "ext": "png",
    "group": "approved"
  },
  {
    "file": "../uploads/approved/Newtuple_OnePager%20%281%29.pdf",
    "thumb": "ref-thumbs/uploads-approved-newtuple-onepager-1.png",
    "title": "Newtuple OnePager (1)",
    "type": "pdf",
    "ext": "pdf",
    "group": "approved"
  },
  {
    "file": "../uploads/Agentic%20Design%20Patterns%20-%20LinkedIn%20Carousel.pdf",
    "thumb": "ref-thumbs/uploads-agentic-design-patterns-linkedin-carousel.png",
    "title": "Agentic Design Patterns LinkedIn Carousel",
    "type": "pdf",
    "ext": "pdf",
    "group": "reference"
  },
  {
    "file": "../uploads/AI-Governance-Moment.pptx%20%282%29.pptx",
    "thumb": "ref-thumbs/uploads-ai-governance-moment-pptx-2.png",
    "title": "AI Governance Moment.pptx (2)",
    "type": "deck",
    "ext": "pptx",
    "group": "reference"
  },
  {
    "file": "../uploads/image.png",
    "thumb": "ref-thumbs/uploads-image.png",
    "title": "image",
    "type": "image",
    "ext": "png",
    "group": "reference"
  },
  {
    "file": "../uploads/link.html",
    "thumb": "ref-thumbs/uploads-link.png",
    "title": "link",
    "type": "page",
    "ext": "html",
    "group": "reference"
  }
];
