#!/usr/bin/env python3
"""
build_library.py — index approved/published reference assets for the Brand Studio,
generating real first-page thumbnails.

Scans the references folder (default: ../uploads) and writes:
  - studio/references.js          (window.NT_REFERENCES manifest)
  - studio/ref-thumbs/*.png       (thumbnails: Quick Look for PDFs/decks, sips for images)

Workflow: drop approved files into  uploads/approved/  then run:
    python tools/build_library.py

macOS only for thumbnails (uses qlmanage + sips). Without them it still writes the
manifest; doc cards just fall back to a typed placeholder.
"""
import json, os, shutil, subprocess, sys, tempfile, urllib.parse

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SRC  = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, 'uploads')
STUDIO = os.path.join(ROOT, 'studio')
OUT  = os.path.join(STUDIO, 'references.js')
THUMBS = os.path.join(STUDIO, 'ref-thumbs')

KIND_BY_EXT = {
    '.png':'image', '.jpg':'image', '.jpeg':'image', '.gif':'image', '.webp':'image', '.svg':'image',
    '.pdf':'pdf', '.pptx':'deck', '.ppt':'deck', '.key':'deck',
    '.docx':'doc', '.doc':'doc', '.html':'page', '.htm':'page',
}
SKIP_SUBSTR = ('colors_and_type',)
THUMB_MAX = 900


def title_from(name):
    return ' '.join(os.path.splitext(name)[0].replace('_', ' ').replace('-', ' ').split()).strip()


def slug(rel):
    s = ''.join(c if c.isalnum() else '-' for c in os.path.splitext(rel)[0].lower())
    return '-'.join(filter(None, s.split('-')))


def have(cmd):
    return shutil.which(cmd) is not None


def make_thumb(abs_path, kind, dest):
    """Render a thumbnail PNG to dest. Returns True on success."""
    try:
        if kind == 'image' and have('sips'):
            r = subprocess.run(['sips', '-s', 'format', 'png', '-Z', str(THUMB_MAX), abs_path, '--out', dest],
                               capture_output=True, timeout=60)
            return r.returncode == 0 and os.path.exists(dest)
        if have('qlmanage'):
            with tempfile.TemporaryDirectory() as td:
                subprocess.run(['qlmanage', '-t', '-s', str(THUMB_MAX), '-o', td, abs_path],
                               capture_output=True, timeout=120)
                pngs = [f for f in os.listdir(td) if f.lower().endswith('.png')]
                if pngs:
                    shutil.move(os.path.join(td, pngs[0]), dest)
                    return os.path.exists(dest)
    except Exception:
        return False
    return False


def main():
    if not os.path.isdir(SRC):
        sys.exit(f"references folder not found: {SRC}")
    if os.path.isdir(THUMBS):
        shutil.rmtree(THUMBS)
    os.makedirs(THUMBS, exist_ok=True)

    found = {}  # basename(lower) -> record (dedupe; prefer approved/)
    for dirpath, _dirs, files in os.walk(SRC):
        for fn in sorted(files):
            if fn.startswith('.'):
                continue
            ext = os.path.splitext(fn)[1].lower()
            if ext not in KIND_BY_EXT or any(s in fn.lower() for s in SKIP_SUBSTR):
                continue
            abs_path = os.path.join(dirpath, fn)
            rel_repo = os.path.relpath(abs_path, ROOT)
            approved = 'approved' in rel_repo.lower()
            key = fn.lower()
            if key in found and not approved:
                continue  # keep existing (approved wins)
            found[key] = (abs_path, fn, ext, approved, rel_repo)

    items = []
    for abs_path, fn, ext, approved, rel_repo in found.values():
        kind = KIND_BY_EXT[ext]
        rel_studio = os.path.relpath(abs_path, STUDIO)
        file_url = '/'.join(urllib.parse.quote(p) for p in rel_studio.split(os.sep))
        thumb_url = None
        dest = os.path.join(THUMBS, slug(rel_repo) + '.png')
        if make_thumb(abs_path, kind, dest):
            thumb_url = 'ref-thumbs/' + urllib.parse.quote(os.path.basename(dest))
        items.append({
            'file': file_url, 'thumb': thumb_url, 'title': title_from(fn),
            'type': kind, 'ext': ext.lstrip('.'), 'group': 'approved' if approved else 'reference',
        })

    items.sort(key=lambda x: (0 if x['group'] == 'approved' else 1, x['title'].lower()))
    with open(OUT, 'w') as f:
        f.write("/* Newtuple approved reference assets — GENERATED by tools/build_library.py.\n"
                "   Drop files into uploads/approved/ then re-run. Do not hand-edit. */\n")
        f.write('window.NT_REFERENCES = ' + json.dumps(items, indent=2, ensure_ascii=False) + ';\n')

    ok = sum(1 for it in items if it['thumb'])
    print(f"indexed {len(items)} reference(s); {ok} with thumbnails")
    for it in items:
        mark = '🖼' if it['thumb'] else '·'
        print(f"  {mark} [{it['type']:5}] {it['title']}  ({it['group']})")
    print(f"wrote {os.path.relpath(OUT, ROOT)} and thumbnails in studio/ref-thumbs/")


if __name__ == '__main__':
    main()
